### ISSUE TITLE
SCCM Lab 

### ISSUE THREAD

**Issue by MOmovictor** [Orange-Cyberdefense/GOAD#220]
My host is Win10 and set up the GOAD lab successfully. Then used the same method to set up SCCM lab.

`~/Desktop/GOAD/ansible$ ansible-playbook -i ../ad/SCCM/data/inventory -i ../ad/SCCM/providers/vmware/inventory main.yml`

It spent more than 1 hour when I set up it. Then I find where progress suspended.

```
- name: install MECM (this one take an eternity ~ 1 hour  )
  win_shell: .\setup.exe /SCRIPT "C:\setup\ConfigMgrAutoSave.ini"
  args:
    chdir: C:\setup\cd.retail.LN\SMSSETUP\BIN\X64
  vars:
    ansible_become: yes
    ansible_become_method: runas
    domain_name: "{{domain}}"
    ansible_become_user: "{{domain_username}}"
    ansible_become_password: "{{domain_password}}"
```

Then decided to manual install it, then I got the following error:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/25227103/32cc7ba9-d818-4dd3-824d-ac18ffa74da5)
